apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnode-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vnode-app
  template:
    metadata:
      labels:
        app: vnode-app
    spec:
      containers:
      - name: vnode-app-container
        image: vcats/vnode-test:0.0.35
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vnode-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32000
  selector:
    app: vnode-app
