apiVersion: apps/v1
kind: Deployment
metadata:
  name: vnode-app-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vnode-app
  template:
    metadata:
      labels:
        app: vnode-app
    spec:
      containers:
      - name: vnode-app-container
        image: vcats/vnode-test:0.0.50
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vnode-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32000
  selector:
    app: vnode-app
---
apiVersion: v1
kind: Service
metadata:
  name: vnode-app-svc2
spec:
  selector:
    app: stream-001
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vnode-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: test1.ctict.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vnode-app-svc2
                port:
                  name: http
